### ISSUE TITLE
Upgrade to 2.6.0 breaks react-native-fbsdk#0.6.3

### ISSUE THREAD

**Issue by danieloprado** [bugsnag/bugsnag-react-native#180]
### Expected behavior
Successfully build android project

### Observed behavior
Modifying the **android/build.gradle** to the new maven repository breaks the facebook sdk build.

```groovy
// React Default
maven { url "$rootDir/../node_modules/react-native/android" }

// Bugsnag v2.6.0
maven { url 'https://maven.google.com' }
```
Error:
```bash
:react-native-fbsdk:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/danielprado/projects/fitfood-app/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/FBAppEventsLoggerModule.java:209: error: cannot find symbol
     @ReactMethod(isBlockingSynchronousMethod = true)
                                                ^
  symbol:   method isBlockingSynchronousMethod()
  location: @interface ReactMethod
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/danielprado/projects/fitfood-app/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/Utility.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
```

### Steps to reproduce
Install **react-native-fbsdk#0.6.3** and **bugsnag-react-native#2.6.0** 

### Version
2.6.0

**Comment by kattrali** [comment]
Thanks for the report, @danieloprado. Instead of removing the default React maven repository, can you instead append the Google repository, like so:

```groovy
repositories {
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven { url 'https://maven.google.com' }
}
```

The relevant dependencies should be fetched from whichever source they are first available, preferring the default repository in within the project.

**Comment by danieloprado** [comment]
It worked! Thanks!

**Comment by kattrali** [comment]
Great! I've updated the docs to make this clearer as well. Thanks again!

**Comment by jose920405** [comment]
@kattrali 

Still happening to me in `0.7.0`

This is my `build.gradle` file

```
buildscript {
    repositories {
        jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
}

```
