### ISSUE TITLE
Attempt to invoke virtual method 'boolean com.bugsnag.android.Error.shouldIgnoreClass()' on a null object reference

### ISSUE THREAD

**Issue by ghsdh3409** [bugsnag/bugsnag-react-native#381]
### Description

* After I upgrade to `2.22.0`, the following error is reported for some users.
* Attempt to invoke virtual method 'boolean com.bugsnag.android.Error.shouldIgnoreClass()' on a null object reference.
* This is raised on app execution immediately.
* Only reported on Android.

### Issue

* Attempt to invoke virtual method 'boolean com.bugsnag.android.Error.shouldIgnoreClass()' on a null object reference.

### Environment

Library versions: 2.22.0

```shell

```

- cocoapods version (if any) (`pod -v`):
- iOS/Android version(s): Android: 8.0
- simulator/emulator or physical device?: Physical device
- debug mode or production?: production

- [ ] (iOS only) `[BugsnagReactNative start]` is present in the
  `application:didFinishLaunchingWithOptions:` method in your `AppDelegate`
  class?
- [ ] (Android only) `BugsnagReactNative.start(this)` is present in the
  `onCreate` method of your `MainApplication` class?

### Example Repo

- [ ] Create a minimal repository that can reproduce the issue after running
  `yarn install` and `react-native run-ios`/`react-native run-android`
- [ ] Link to it here:

### Example code snippet

```js
import { Client, Configuration } from 'bugsnag-react-native';

// (Insert code sample to reproduce the problem)
```

<details><summary>Error messages:</summary>

```

```
</details>

**Comment by ghsdh3409** [comment]
Should I put `BugsnagReactNative.start(this)` in `MainApplication` class?

**Comment by mattdyoung** [comment]
Hi @ghsdh3409

Yes, `BugsnagReactNative.start(this)` should be in the `onCreate` method of your `MainApplication` class.

If you're still having issues with this can you provide a full code example which demonstrates the issue so we can try and reproduce?

Have you taken a look at our React Native example apps here?
https://github.com/bugsnag/bugsnag-react-native/tree/master/examples

Thanks!

**Comment by ghsdh3409** [comment]
@mattdyoung 
Thanks for your response!
After I add `BugsnagReactNative.start(this)`, I will check this issue again!

**Comment by andrewtelkamp** [comment]
DId this fix work @ghsdh3409?

**Comment by andrewtelkamp** [comment]
We're seeing the same issue, but when I add the `BugsnagReactNative.start(this)` line to onCreate, the app crashes without error and I see this in terminal

```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
```

**Comment by ghsdh3409** [comment]
@andrewtelkamp @mattdyoung 
It does not work! Even if I added `BugsnagReactNative.start(this)`, it has the same issue!

**Comment by EmilScherdin** [comment]
I have the same issue here. Seeing a lot of crashes regarding this. About 2% of our users. Got it after updating to `2.22.0`

**Comment by abigail-bugsnag** [comment]
We believe that this is a defect in our 4.16.+ notifiers of bugsnag-android. This will also affect users of our 2.22.+ notifiers of bugsnag-react-native.

We are investigating this now and will look to release a fix for this soon.

**Comment by bengourley** [comment]
This was fixed in [`bugsnag-android@v4.17.1`](https://github.com/bugsnag/bugsnag-android/releases/tag/v4.17.1) and is included in the latest `bugsnag-react-native` release: [`v2.22.2`](https://github.com/bugsnag/bugsnag-react-native/releases/tag/v2.22.2).

**Comment by ghsdh3409** [comment]
Even though I upgrade `bugsnag-react-native` to v2.22.2, It stills exists!

**Comment by fractalwrench** [comment]
@ghsdh3409 I've inspected your project for Hayanmind and have observed that errors are still coming in, when the`app.versionCode` equals 125/126. When I updated the search 
filter to only include errors from the latest release (as displayed in the attached screenshot), I didn't observe any incidences of this error.

Would you be able to confirm what the `versionCode` of the Android app was which contained the fix? I believe these errors may be occurring on devices which have not updated to a later version of the app, which would contain the fix.

<img width="497" alt="Screenshot 2019-07-29 at 13 01 38" src="https://user-images.githubusercontent.com/11800640/62047006-47279a80-b201-11e9-854f-f9e594f21f0d.png">

**Comment by ghsdh3409** [comment]
@fractalwrench 
The latest android version code is `126`.
I checked this error is also raised on the latest android version (126) from firebase crashlytics.

<img width="790" alt="스크린샷 2019-07-29 오후 9 52 13" src="https://user-images.githubusercontent.com/6203798/62049909-33088b00-b24b-11e9-9aed-20b9e47c5e8b.png">

**Comment by ghsdh3409** [comment]
@EmilScherdin 
`v2.22.2` works for you?

**Comment by EmilScherdin** [comment]
@ghsdh3409 Haven’t had the time to try it yet. Will not until mid/end of august

**Comment by fractalwrench** [comment]
@ghsdh3409 the line numbers in that stacktrace align with the version of bugsnag-android used in [v2.22.1](https://github.com/bugsnag/bugsnag-android/blob/v4.16.1/sdk/src/main/java/com/bugsnag/android/Client.java#L901) of bugsnag-react-native, but not [v2.22.2](https://github.com/bugsnag/bugsnag-android/blob/v4.17.1/bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java#L901). 

Therefore it appears that these errors are either occurring on devices which have not updated to a later version of the app, or that the latest version of your app has not been updated to use v2.22.2 of bugsnag-react-native. If you are using codepush, you will need to release via the Play Store to deploy the fix to the native layer. It may also be worth checking that the `bugsnag-react-native` package in your `node_modules` corresponds with what is in the `package.json`.

**Comment by ghsdh3409** [comment]
@fractalwrench 
I also doubt myself. So, I upgrade `bugsnag-react-native` to `v2.22.2` again and release to Play Store.
But, It has same error and same stacktrace.

Can I check my sdk version on the bugsnag dashboard?

**Comment by fractalwrench** [comment]
@ghsdh3409 we can check the SDK version for you, if you're happy to send a URL of an example error to support@bugsnag.com referencing this issue.

**Comment by ghsdh3409** [comment]
@fractalwrench Okay, I will send email! Thanks!

**Comment by ghsdh3409** [comment]
@fractalwrench 
I checked that my `bugsnag-android` was `4.16.1`!
Also, I checked that even though I upgraded `bugsnag-react-native` to `2.22.2`, `bugsnag-android` was still `4.16.1`. I checked that from Android Studio > External Libraries.

Previously, I upgraded like the below.
```
rm -rf node_modules
yarn
./gradlew clean
```

After I contacted with ` support@bugsnag.com`, I upgraded `bugsnag-react-native` by the following command he proposed.
```
rm -rf node_modules
yarn
./gradlew clean
rm -rf ~/.gradle/caches
```

And then, I finally get `bugsnag-android 4.17.1`. This issue is not raised anymore!
