### ISSUE TITLE
Javascript errors appear as minimal `com.bugsnag.JavascriptException`

### ISSUE THREAD

**Issue by sampsonjoliver** [bugsnag/bugsnag-react-native#391]
### Description
Been using bugsnag for quite a while now with good success. Recently, upgrading has caused an issue with the reported errors coming in through production. Mostly on Android so far but I believe this is on both platforms.

### Issue
In a new release we upgraded the react-native-bugsnag client from `2.9.5` up to `2.22.2`. Since then, all native errors appear to be caught correctly, but we seem to have received no javascript errors without "incomplete report".

![Bugsnag](https://user-images.githubusercontent.com/9619248/62269431-667b2d80-b476-11e9-91e0-ad8084f9f0f3.png)

The breadcrumbs for these show some may be Network errors, which were a class of error that was previously caught and shown clearly in our bugsnag dashboard.

With 2.22.2:
![image](https://user-images.githubusercontent.com/9619248/62334055-6d06b500-b509-11e9-9100-d9e4119b0e35.png)

Previously, With 2.9.5
![image](https://user-images.githubusercontent.com/9619248/62334092-8f98ce00-b509-11e9-8dda-1d203efb125f.png)

Library versions:

```shell
├─ bugsnag-react-native@2.12.2
├─ react-native-code-push@5.6.0
└─ react-native@0.57.5
```

- [ ] (iOS only) `[BugsnagReactNative start]` is present in the
  `application:didFinishLaunchingWithOptions:` method in your `AppDelegate`
  class?
- [ ] (Android only) `BugsnagReactNative.start(this)` is present in the
  `onCreate` method of your `MainApplication` class?

**Comment by mattdyoung** [comment]
Hi @sampsonjoliver 

Thanks for your report. We're not sure what could have caused that behaviour but it does sound suspicious so we'll investigate and see if we can reproduce.

**Comment by mattdyoung** [comment]
@sampsonjoliver just a quick clarification - on your listed library versions above it shows `bugsnag-react-native@2.12.2`. Can you confirm you definitely upgraded to `2.22.2`, not `2.12.2`?

**Comment by sampsonjoliver** [comment]
@mattdyoung thanks for the reply, and good observation! I must have not reinstalled node modules locally when I ran `yarn list` before, apologies. I've just checked out the commit sha of our last tagged production release, which contains this issue, and after a `yarn install` it is definitely `2.22.2`.

This is also the git diff of that commit:

![image](https://user-images.githubusercontent.com/9619248/62432497-624f5880-b773-11e9-9136-15bb0a3c9098.png)

We run our builds off of Bitrise via CI so I'm certain the production release containing this issue will be running `2.22.2`.

There are also no other configuration changes that should affect Bugsnag other than just doing this yarn package update, so unfortunately I don't think there's much more context I can provide to help. Our efforts to produce a javascript crash in development seem to send through reports correctly.

I'll be doing a rollback to `2.9.5` later this week to production, and will advise if these reports disappear and revert back to as they were before.

**Comment by yaronlevi** [comment]
We are also experiencing this issue.
We've just upgraded to bugsnag-react-native@2.22.2.
React Native is @0.59.10.

In contrast to the @sampsonjoliver problem, we **do** receive some JS errors with correct source mapping as usual.
But a week ago, after we updated to 2.22.2 we started to see these errors:
<img width="1328" alt="Screen Shot 2019-08-12 at 17 28 03" src="https://user-images.githubusercontent.com/5398977/62872798-e468ef80-bd26-11e9-98b8-71cb11458fe2.png">

Errors are coming only from **Android** users.

The error message itself is:

> com.bugsnag.JavaScriptExceptionunknown method:0

here is another screenshot of the error's body:

<img width="981" alt="Screen Shot 2019-08-12 at 17 35 42" src="https://user-images.githubusercontent.com/5398977/62873215-ae783b00-bd27-11e9-8ef1-b16fc780ba4f.png">

**Comment by sampsonjoliver** [comment]
I can also confirm this is occurring only on Android, iOS errors seem to be coming through okay.

**Comment by tomlongridge** [comment]
@sampsonjoliver / @yaronlevi - can you confirm whether you have any dependencies for bugsnag-android in your build.gradle file(s) in your modules?

We believe this may be caused by a mismatch in library version.

Please check our manual linking documentation (https://docs.bugsnag.com/platforms/react-native/react-native/manual-linking-guide) for how this should look:
```
dependencies {
     implementation project(':bugsnag-react-native')
}
```
Any references to dependencies under `com.bugsnag` namespace should be removed.

**Comment by tomlongridge** [comment]
@sampsonjoliver - additionally, we can see that you are getting JS exceptions from Android that are not of this type so we're wondering if the missing stacktrace (and minimal report) is a more specific problem with this area of code that involved a network call.

We've tried to reproduce this based on the error message above by calling off to a webserver that responds with a 400 status, but this doesn't give us the same issue. Would you be able to assist us in getting a reproduction case? Possibly by sharing some code snippets or a cut down app?

Feel free to contact us at support@bugsnag.com if you'd rather not do this on Github.

**Comment by yaronlevi** [comment]
@tomlongridge 

Our settings.gradle contains:
```
include ':bugsnag-react-native'
project(':bugsnag-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/bugsnag-react-native/android')
```

Our build.gradle contains:
`compile project(':bugsnag-react-native')`

Maybe using **compile** and not **implementation** causing this?

Regarding clearing Gradle caches, we run the build in Bitrise, so is it relevant?

We have no other references to com.bugsnag in the code base.

**Comment by tomlongridge** [comment]
@yaronlevi - we do not believe this will be due to use of **compile** however as Bitrise supports caching Gradle dependencies, it could be relevant.

I see from your project that you have some Network Error messages in your breadcrumbs too. Are you able to reliably reproduce this error locally and/or isolate the application code that could be triggering the event?

**Comment by yaronlevi** [comment]
@tomlongridge 
Regarding clearing the Gradle cache, how can we do this in an automated environment like Bitrise?

Regarding the network errors you've mentioned.

In the Bugsnag dashboard I see two variants of the error:

**com.bugsnag.JavaScriptExceptionunknown method:0**

and 

**com.bugsnag.JavaScriptExceptionMainActivity**

The method:0 variant has breadcrumbs **without** network calls like these:


```
Error Occurred0s before |  
-- | --
  | SCREEN_ON1s after | Intent Actionandroid.intent.action.SCREEN_ON
  | SCREEN_OFF1s after | Intent Actionandroid.intent.action.SCREEN_OFF
  | DREAMING_STOPPED1s after | Intent Actionandroid.intent.action.DREAMING_STOPPED
  | DREAMING_STARTED1s after | Intent Actionandroid.intent.action.DREAMING_STARTED
  | CLOSE_SYSTEM_DIALOGS1s after | Intent Actionandroid.intent.action.CLOSE_SYSTEM_DIALOGSreasondream
  | MainActivity0s before | ActivityLifecycleonStop()
  | MainActivity0s before | ActivityLifecycleonSaveInstanceState()
  | MainActivity0s before | ActivityLifecycleonPause()
  | DREAMING_STOPPED0s before | Intent Actionandroid.intent.action.DREAMING_STOPPED
  | DREAMING_STARTED0s before | Intent Actionandroid.intent.action.DREAMING_STARTED
  | CLOSE_SYSTEM_DIALOGS0s before | Intent Actionandroid.intent.action.CLOSE_SYSTEM_DIALOGSreasondream
  | MainActivity0s before | ActivityLifecycleonResume()
  | MainActivity0s before | ActivityLifecycleonStart()
  | MainActivity0s before | ActivityLifecycleonCreate()


```

The mainActivity variant has breadcrumbs **with** network calls like these:


```
Error Occurred0s before |  
-- | --
  | com.bugsnag.JavaScriptExceptio1s after | message
  | com.bugsnag.JavaScriptExceptio1s after | message
  | com.bugsnag.JavaScriptExceptio1s after | message
  | com.bugsnag.JavaScriptExceptio1s after | message
  | com.bugsnag.JavaScriptExceptio1s after | message
  | com.bugsnag.JavaScriptExceptio3s before | messageNetwork Error
  | com.bugsnag.JavaScriptExceptio3s before | messageNetwork Error
  | com.bugsnag.JavaScriptExceptio5s before | messageNetwork Error
  | com.bugsnag.JavaScriptExceptio8s before | messageNetwork Error
  | com.bugsnag.JavaScriptExceptio8s before | messageNetwork Error
  | com.bugsnag.JavaScriptExceptio47s before | messageNetwork Error
  | com.bugsnag.JavaScriptExceptio50s before | messageNetwork Error
  | com.bugsnag.JavaScriptExceptio53s before | messageNetwork Error
  | MainActivity1m, 13s before | ActivityLifecycleonResume()
  | MainActivity1m, 13s before | ActivityLifecycleonStart()
  | MainActivity1m, 13s before | ActivityLifecycleonCreate()
```

**Comment by sampsonjoliver** [comment]
Hey @tomlongridge , we do have in our `app/build.gradle` the dependency
```
depdendencies {
    ...
    implementation project(':bugsnag-react-native')
}
```

and in the `settings.gradle`

```
include ':bugsnag-react-native'
project(':bugsnag-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/bugsnag-react-native/android')
```

and in `MainApplication.java`
```
import com.bugsnag.BugsnagReactNative;

...

  protected List<ReactPackage> getPackages() {
    return ... BugsnagReactNative.getPackage() ...
  }
```

So far my attempts to reproduce these minimal errors has just resulted in regular, fully-realised errors coming through, so I am at a loss for giving a minimal reproduction, sorry.

**Comment by sampsonjoliver** [comment]
I can say however, that producing a new build (through Bitrise as per usual) with the bugsnag-react-native dependency set to `2.9.5` again seems to be reporting errors correctly. We are on a slow rollout currently though so there's still room for me to be proven wrong.

For your reference, our application version 2.3.3 is the one containing bugsnag 2.22.2, and all other versions are at 2.9.5.

**Comment by yaronlevi** [comment]
Any new insights?

**Comment by abigail-bugsnag** [comment]
@sampsonjoliver @yaronlevi A fix has been released for this in the latest bugsnag-react-native: https://github.com/bugsnag/bugsnag-react-native/releases/tag/v2.22.6

**Comment by tomlongridge** [comment]
To clarify, this latest release fixes the parsing of the exception to correctly report the underlying Javascript exception. However, from the discussion above, these will still appear as "minimal reports" - suggesting that there is a problem with the JSON encoding/decoding of the crash report file. However, #393 removes one of the uncertainties in the behaviour you are seeing.

**Comment by tomlongridge** [comment]
@yaronlevi - are you able to repro the issue in your app with the latest build?

**Comment by yaronlevi** [comment]
@tomlongridge I will install 2.22.6 in the next couple of days and report back with results. It might take a few days for the CodePush bundle to bubble up to all the users.

**Comment by mattdyoung** [comment]
@sampsonjoliver @yaronlevi
We've had reports from other customers of unexpectedly high volumes of these "minimal report" errors so we've been doing further investigation and are still trying to identify the error condition which is resulting these being captured.

These errors are not currently actionable, and we suspect in some cases they may be false positives not relating to a real crash. We've therefore just deployed a backend change to prevent these from being reported until we've diagnosed the cause and released a fix. The backend change will take immediate effect so you'll stop seeing these reported for the time being without needing to perform a library update.

**Comment by yaronlevi** [comment]
We've upgraded to 2.22.6 and it seems to be working fine - the 'com.bugsnag.JavascriptException' error is gradually disappearing from our dashboard 👍

**Comment by abigail-bugsnag** [comment]
@sampsonjoliver @yaronlevi
We have just released a new version of `bugsnag-react-native` ([v2.23.1](https://github.com/bugsnag/bugsnag-react-native/releases/tag/v2.23.1)) which fixes the issue where a minimal error is seen with `com.bugsnag.JavascriptException`.
This version also provides us some additional diagnostics so that we can better identify if there are other causes of these "minimal report" errors.
We would recommend updating to this latest version.
