### ISSUE TITLE
v2.23.3 does not compile for iOS

### ISSUE THREAD

**Issue by antoinerousseau** [bugsnag/bugsnag-react-native#433]
### Description

I upgraded `bugsnag-react-native` from 2.23.2 to 2.23.3 with Yarn, and ran `pod install` in `ios/`, but it broke the build.

### Issue
> ❌  error: node_modules/bugsnag-react-native/cocoa/vendor/bugsnag-cocoa/Configurations/Config.xcconfig: unable to open file (in project "Bugsnag") (in target 'BugsnagStatic' from project 'Bugsnag')

### Environment

Library versions:

```shell
yarn list v1.19.2
├─ bugsnag-react-native@2.23.2
└─ react-native@0.59.10
```

- cocoapods version (if any) (`pod --version`): 1.8.4
- iOS/Android version(s): iOS, N/A
- simulator/emulator or physical device?: N/A
- debug mode or production?: production

- [ ] (iOS only) `[BugsnagReactNative start]` is present in the
  `application:didFinishLaunchingWithOptions:` method in your `AppDelegate`
  class? no
- [ ] (Android only) `BugsnagReactNative.start(this)` is present in the
  `onCreate` method of your `MainApplication` class? no

**Comment by phillipsam** [comment]
Hi @antoinerousseau - does this issue persist if you delete your node modules directory and reinstall?

**Comment by antoinerousseau** [comment]
@phillipsam just tried it and still fails

```
[13:10:27]: $ set -o pipefail && xcodebuild -workspace ./ios/artefac.xcworkspace -scheme artefac -destination 'generic/platform=iOS' -archivePath /Users/antoine/Library/Developer/Xcode/Archives/2019-12-17/artefac\ 2019-12-17\ 13.10.27.xcarchive archive | tee /Users/antoine/Library/Logs/gym/artefac-artefac.log | xcpretty
[13:10:32]: ▸ ❌  error: /Users/antoine/Sites/artefac/mobile/node_modules/bugsnag-react-native/cocoa/vendor/bugsnag-cocoa/Configurations/Config.xcconfig: unable to open file (in project "Bugsnag") (in target 'BugsnagStatic' from project 'Bugsnag')
[13:10:32]: ▸ ❌  error: /Users/antoine/Sites/artefac/mobile/node_modules/bugsnag-react-native/cocoa/vendor/bugsnag-cocoa/Configurations/Config.xcconfig: unable to open file (in project "Bugsnag") (in target 'BugsnagStatic' from project 'Bugsnag')
[13:10:32]: ▸ ❌  error: /Users/antoine/Sites/artefac/mobile/node_modules/bugsnag-react-native/cocoa/vendor/bugsnag-cocoa/Configurations/Config.xcconfig: unable to open file (in project "Bugsnag") (in target 'BugsnagStatic' from project 'Bugsnag')
[13:10:32]: ▸     The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.2.99. (in target 'RCTVideo' from project 'RCTVideo')
[13:10:32]: ▸     The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.2.99. (in target 'RNFS' from project 'RNFS')
[13:10:32]: ▸ ** ARCHIVE FAILED **
```

FYI I'm using fastlane 2.137.0, Xcode 11.3 and macOS 10.15.2 (Catalina).

**Comment by mattdyoung** [comment]
@antoinerousseau 
We're unable to reproduce this. Do you have a reproduction case you can share with us?

It would also be useful to see how your `Podfile` is configured as i believe you're using React Native  0.59.10 which is before Cocoapods was introduced to React Native by default.

**Comment by loga4** [comment]
@antoinerousseau remove target from Xcode -> Libraries

**Comment by antoinerousseau** [comment]
@mattdyoung here is my `Podfile`:

```
platform :ios, '9.3'

target 'artefac' do
  use_frameworks!
  pod 'ViroReact', :path => '../node_modules/react-viro/ios/'
  pod 'ViroKit', :path => '../node_modules/react-viro/ios/dist/ViroRenderer/'

end
```

module is linked manually because of restrictions in other librairies I use.

but it's fine i'm just going to keep using v2.23.2 until we can upgrade RN :)

**Comment by fbartho** [comment]
@mattdyoung We're not using Cocoapods, we're exhibiting this issue on react-native 0.59, and we don't see the Configurations directory in the node_modules/bugsnag-react-native/ directory when we checked.

Is Cocoapods required now?

**Comment by fbartho** [comment]
We've had bugsnag-react-native integrated for a while -- currently on 2.23.1, and it was a dependabot PR that updated us into triggering this issue.

**Comment by mattdyoung** [comment]
@fbartho 
No Cocoapods is not required on earlier versions of React Native. You should be able to link to bugsnag-react-native using the instructions for React Native < 0.60 shown here:
https://docs.bugsnag.com/platforms/react-native/react-native/#installation
```
react-native link bugsnag-react-native
```

**Comment by fbartho** [comment]
That is our current setup. Despite that we're exhibiting the error:
```
error: node_modules/bugsnag-react-native/cocoa/vendor/bugsnag-cocoa/Configurations/Config.xcconfig: unable to open file (in project "Bugsnag") (in target 'BugsnagStatic' from project 'Bugsnag')
```

**Comment by patik** [comment]
I'm having the same error. RN 0.59, Cocoapods 1.8.4. Clearing node_modules and re-running `yarn add bugsnag-react-native` doesn't help.

**Comment by antoinedelp** [comment]
I had the same issue. Reverting to bugsnag-react-native **2.23.2** fixes it for me.
I do not have the same problem on another project running on react-native 0.61.6

**Comment by Rutvik17** [comment]
I am having the same issue when i upgraded react native from 0.59.10 to 0.60.6
I can not build my project anymore and fails with `node_modules/bugsnag-react-native/cocoa/vendor/bugsnag-cocoa/Configurations/Config.xcconfig: unable to open file (in project "Bugsnag") (in target 'BugsnagStatic' from project 'Bugsnag')`
my bugsnag version is ^2.23.2

**Comment by tienzodi** [comment]
I found and tried to delete Config.xcconfig inside BugsnagReactnative.xcodeproj below Libraries folder then it works. Can you try to find it?
![image](https://user-images.githubusercontent.com/21222786/72214154-365cae00-352f-11ea-9fb0-c1e0e7997f66.png)

**Comment by hndao** [comment]
@tienzodi 
it works for me, thanks!

**Comment by mattdyoung** [comment]
Fixed in [v2.23.5](https://github.com/bugsnag/bugsnag-react-native/releases/tag/v2.23.5)

**Comment by ZeerakHameem32** [comment]
Hi, the app compiles on 2.23.5. But still cannot archive? any help?

**Comment by phillipsam** [comment]
Hi @ZeerakHameem32  - thanks for reaching out. Can you please clarify what issue you are having?

**Comment by ZeerakHameem32** [comment]
Hi, please look at the following screenshot. I am getting this error while archiving iOS build. It runs fine on the emulator though.
<img width="1186" alt="Screenshot 2020-02-05 at 7 35 40 PM" src="https://user-images.githubusercontent.com/51910597/73851360-25ae0800-484f-11ea-96b9-1405cf3e05c6.png">

I tried v2.23.3 & 2.23.5 both had the same error. I am on React native 0.61.5
I just upgraded my react native version to 0.61.5. All other dependencies are set but I am unable to run Bugsnag.

**Comment by phillipsam** [comment]
@ZeerakHameem32 - thanks. I will continue on #148 as it looks closer to the issue you are having.
